### ISSUE TITLE
Update docs.citationstyles.org with release 1.0-20100321

### ISSUE THREAD

**Issue by spl** [citation-style-language/documentation#38]
I was going to report a grammar issue but that I found it had already been fixed in 8ed1a44d6d22213a565dd04022d46611393a2230. Since you do have a release, perhaps you should update the website with it?

**Comment by rmzelle** [comment]
Yeah, I was just brushing up on my git skills this week to figure out how to best maintain multiple branches (since there are a few other typos that should be fixed in multiple versions of the CSL spec). Wasn't exactly sure whether I should be merging branches, cherry-pick, or do something else. It's on the radar, though.

**Comment by spl** [comment]
Cool. :-) There are so many possible workflows and any one of them will
probably work. As an additional consideration, if you already use GitHub
for most things, then using pull requests for all changes gives you things
to comment on and reference in later threads.

**Comment by rmzelle** [comment]
This is now (finally) fixed in the "1.0.1" branch (see https://github.com/citation-style-language/documentation/commit/808a7d9ca7075a361a080dd17c7a6fce92b08646).
