### ISSUE TITLE
Name variable 'original-author' is described as '?'

### ISSUE THREAD

**Issue by jayvdb** [citation-style-language/documentation#42]
http://docs.citationstyles.org/en/stable/specification.html#name-variables

**Comment by rmzelle** [comment]
When I wrote the CSL specification, I tried to come up with a good description of each variable. I couldn't find any description in the email archives on the use case for "original-author" (whose introduction precedes my involvement in the project), hence the "?".

@adam3smith, @bdarcus, any ideas?

**Comment by adam3smith** [comment]
I don't really know either. My guess would be that it could be classical author (Aristotle etc.) that aren't listed as primary authors in an edition of their works, but I don't actually know.

**Comment by bdarcus** [comment]
I think that's right, but my memory is foggy on this, and I'm bummed I
didn't correctly document it, and can't immediately think of the use
case.

I do know it's designed to be coupled with original-title, and there's
some old discussions about this issue (relating also to translated
works) on the zotero forum; see e.g.:

https://forums.zotero.org/discussion/4894/impossible-to-cite-translated-work/

**Comment by zaw-shinoto** [comment]
The "original-author" is indeed handy. 

(1) E.g. in Japanese ancient history, the mythology is often quoted with the name of the modern (18th century and later) scholar rather than the author who is identified as the original author of the piece of writing or art. It should be similar in the histories of other regions.

(2) Translations in general need original author names, as well as original titles etc..

(3) I use this field (together with original title and original publisher) regularly for items in Zotero which are written in East Asian languages. For these entries to be published in Western papers, we need entirely Western input (names, translations or transcriptions). -- So I create an entry with the original data, but I also create at least one entry with data translated into Western writing and languages, the entries are connected in the last tab and get identical citation keys with an add on with the language ID in case of a secondary (translated) entry. -- Although clumsy, several entries for the same item turns out to be the most convenient solution. 

Of course, the original date is related to these entries. 

As a matter of fact, I would love to see these variables (original-author, original-title, original publisher) enhanced, very much like in the multilingual version of Zotero which seems not be developed any longer.

**Comment by bwiernik** [comment]
@zaw-shinoto Multilingual Zotero still exists, now called "Jurism": https://juris-m.github.io
