### ISSUE TITLE
`language`, `journalAbbreviation`, and `shortTitle` fields are missing from specification page

### ISSUE THREAD

**Issue by dsifford** [citation-style-language/documentation#53]
Looks like these fields were added after the initial spec was written (judging by the location of these compared to all the other variables)

https://github.com/citation-style-language/schema/blob/4846e02f0a775a8272819204379a4f8d7f45c16c/csl-data.json#L62-L70

They haven't made it to the [standard variables](http://docs.citationstyles.org/en/1.0.1/specification.html#standard-variables) page of the spec.

**Comment by rmzelle** [comment]
@dsifford, none of these are CSL variables that can be printed by CSL styles. These are all cases where the CSL JSON fields don't map directly to CSL variables.

* The "language" field in CSL JSON is used by the CSL processor (see e.g. http://docs.citationstyles.org/en/1.0.1/specification.html#non-english-items), but since CSL assumes that this field is filled with locale codes (like "en-US"), we never saw the point of allowing people to print the field, so there is no matching CSL variable.
* The CSL JSON format was based on what citeproc-js used/uses. citeproc-js historically used "shortTitle", before CSL added a dedicated variable for the "short" form of "title" (see http://docs.citationstyles.org/en/1.0.1/release-notes.html#new-variables-container-title-short-and-title-short and https://github.com/citation-style-language/schema/issues/113). The same goes for "journalAbbreviation", which was used before CSL added the "container-title-short" CSL variable. The plan is to update CSL JSON to use the CSL variable names.

**Comment by denismaier** [comment]
Can't this be closed? Or what is the required change by now? (Maybe we should add a section about the json schema to the docs?)
